- name: Add RabbitMQ key
  apt_key: url=https://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present
  become: yes

- name: Add RabbitMQ repository
  apt_repository: repo="deb http://www.rabbitmq.com/debian/ testing main" state=present update_cache=yes
  become: yes

- name: Install RabbitMQ
  apt: name=rabbitmq-server state=latest
  become: yes

- name: Enable RabbitMQ management
  rabbitmq_plugin: names=rabbitmq_management state=enabled
  become: yes
  notify:
    - restart rabbitmq
