- name: Obtaining percona public key
  apt_key: url=http://www.percona.com/downloads/RPM-GPG-KEY-percona state=present
  become: yes

- name: Adding percona repository
  apt_repository: repo='deb http://repo.percona.com/apt {{ ansible_distribution_release }} main' state=present update_cache=yes
  become: yes

- name: Adding percona source repository
  apt_repository: repo='deb-src http://repo.percona.com/apt {{ ansible_distribution_release }} main' state=present update_cache=yes
  become: yes

- name: Install percona database server
  action: apt pkg={{ item }} state=present
  become: yes
  with_items:
          - percona-server-server-5.6
          - percona-server-client-5.6
          - percona-toolkit
          - percona-xtrabackup
          - python-mysqldb
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Copy .my.cnf file into the root home folder
  template: src=root-my-cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  become: yes
  notify:
    - restart mysql

- name: Update MySQL root password
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} login_user=root login_password={{ mysql_root_password }} check_implicit_admin=yes
  become: yes
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - localhost

- name: Remove test database
  mysql_db: name=test state=absent
  become: yes

