- name: Update APT cache
  apt: update_cache=yes
  become: yes

- name: Install packages
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - gcc
    - g++
    - vim
    - mc
    - automake
    - dh-make
    - cmake
    - build-essential
    - apache2-utils
    - siege
    - supervisor
