- name: Update APT cache
  apt: update_cache=yes
  become: yes

- name: Install packages
  apt: name={{ item }} state=latest
  become: yes
  with_items:
    - gcc
    - g++
    - vim
    - mc
    - automake
    - dh-make
    - cmake
    - build-essential
    - apache2-utils
    - siege
    - supervisor
    - atop
    - htop
    - iotop
    - tar
    - gzip
    - rsync
    - openssl
    - openssh-server
    - openssh-client
    - sendmail
    - curl
    - wget
